name: Build
on:
  push:
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Configure Project
        runs: cmake -S . -B build BUILD_TESTS=ON

      - name: Build Project
        runs: cmake --build build

      - name: Test Project
        runs: ctest --test-dir build
